# Generated by Django 4.2.2 on 2023-07-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, choices=[('Notebook', 'Notebook'), ('Celular', 'Celular'), ('Acessorio', 'Acessório'), ('Camera', 'Câmera')], max_length=20, null=True)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='static/img')),
            ],
        ),
    ]
